In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the dataset using pandas
df = pd.read_csv('ev_market_2026.csv')

In [3]:
df.head()

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
0,Volkswagen,ID. Buzz,2023,Performance,104880.80,118.7,400.0,234.5,3.04,195.0,...,Truck,54.2,2015.0,4,2,Germany,Luxury,202182,4.00,4
1,Toyota,bZ Compact SUV,2022,Premium,48217.41,58.8,219.0,148.1,5.77,159.0,...,SUV,69.0,1709.0,4,0,Japan,Mid-range,7146,3.56,3
2,GM/Chevrolet,Bolt EV,2024,Premium,49651.12,58.2,225.0,104.9,6.84,148.0,...,Van,77.0,1533.0,4,1,US,Mid-range,16590,3.70,3
3,Kia,Sportage EV,2024,Long Range,38131.56,102.5,349.0,66.5,4.66,176.0,...,SUV,65.8,1935.0,4,2,South Korea,Mid-range,127201,3.81,3
4,Tesla,Model 3,2022,Long Range,144079.87,93.9,314.0,298.5,5.64,165.0,...,SUV,38.3,2229.0,4,2,US,Luxury,196401,3.83,4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand                  2000 non-null   object
 1   model                  2000 non-null   object
 2   year                   2000 non-null   int64
 3   variant                2000 non-null   object
 4   price_usd              2000 non-null   float64
 5   battery_capacity_kwh   2000 non-null   float64
 6   range_miles            2000 non-null   float64
 7   charging_speed_kw      2000 non-null   float64
 8   acceleration_0_60_mph  2000 non-null   float64
 9   top_speed_mph          2000 non-null   float64
 10  horsepower             2000 non-null   float64
 11  torque_nm              2000 non-null   float64
 12  drive_type             2000 non-null   object
 13  seating_capacity       2000 non-null   int64
 14  body_type              2000 non-null   object
 15  cargo_volume_cubic_ft  2000 non-null   float64
 16  weight_kg              2000 non-null   float64
 17  safety_rating          2000 non-null   int64
 18  autopilot_level        2000 non-null   int64
 19  country_of_origin      2000 non-null   object
 20  market_segment         2000 non-null   object
 21  annual_sales_units     2000 non-null   int64
 22  customer_rating        2000 non-null   float64
 23  warranty_years         2000 non-null   int64
dtypes: float64(11), int64(6), object(7)
memory usage: 375.1+ KB

In [5]:
# Summary statistics using .describe()
df.describe(include='all')

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
count,2000,2000,2000.000000,2000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000,2000.000000,2000.000000,2000.000000,2000.000000,2000,2000,2000.000000,2000.000000,2000.000000
unique,20,76,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,...,6,NaN,NaN,NaN,NaN,6,4,NaN,NaN,NaN
top,Tesla,Model S,NaN,Base,NaN,NaN,NaN,NaN,NaN,NaN,...,Truck,NaN,NaN,NaN,NaN,US,Premium,NaN,NaN,NaN
freq,434,93,NaN,420,NaN,NaN,NaN,NaN,NaN,NaN,...,427,NaN,NaN,NaN,NaN,774,712,NaN,NaN,NaN
mean,NaN,NaN,2024.028500,NaN,78873.907150,74.662800,261.825500,155.206300,5.630635,164.884500,...,NaN,46.105850,1886.164500,4.377000,1.124500,NaN,NaN,129653.592000,3.572045,4.579000
std,NaN,NaN,1.410561,NaN,35296.621782,20.082879,71.028238,80.982301,1.417733,20.781244,...,NaN,19.850264,383.772906,0.661127,0.919469,NaN,NaN,105775.154465,0.270398,1.218812
min,NaN,NaN,2020.000000,NaN,16394.330000,40.000000,150.000000,50.000000,2.500000,118.000000,...,NaN,15.000000,1500.000000,3.000000,0.000000,NaN,NaN,656.000000,3.000000,3.000000
25%,NaN,NaN,2023.000000,NaN,52325.920000,58.475000,204.000000,90.975000,4.620000,148.000000,...,NaN,28.175000,1570.000000,4.000000,0.000000,NaN,NaN,44296.500000,3.380000,4.000000
50%,NaN,NaN,2024.000000,NaN,73013.015000,75.100000,261.000000,132.100000,5.670000,165.000000,...,NaN,41.250000,1740.500000,4.000000,1.000000,NaN,NaN,111188.000000,3.560000,4.000000
75%,NaN,NaN,2025.000000,NaN,99780.157500,87.550000,310.000000,217.300000,6.770000,181.000000,...,NaN,64.700000,2149.500000,5.000000,2.000000,NaN,NaN,202496.750000,3.750000,5.000000
max,NaN,NaN,2026.000000,NaN,269775.200000,119.900000,447.000000,349.900000,8.000000,200.000000,...,NaN,80.000000,3000.000000,5.000000,3.000000,NaN,NaN,499717.000000,4.510000,8.000000

In [6]:
# Checking if missing data or null values are present in the dataset
df.isnull().sum()

brand                    0
model                    0
year                     0
variant                  0
price_usd                0
battery_capacity_kwh     0
range_miles              0
charging_speed_kw        0
acceleration_0_60_mph    0
top_speed_mph            0
horsepower               0
torque_nm                0
drive_type               0
seating_capacity         0
body_type                0
cargo_volume_cubic_ft    0
weight_kg                0
safety_rating            0
autopilot_level          0
country_of_origin        0
market_segment           0
annual_sales_units       0
customer_rating          0
warranty_years           0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
#Delete Redundent and Unecessary Columns
df = df.drop(columns=['battery_capacity_kwh','charging_speed_kw','drive_type','top_speed_mph'])

In [11]:
#Add More Meaningful Columns
df["range_per_kwh"] = df["range_miles"] / df["battery_capacity_kwh"]
df["price_per_mile"] = df["price_usd"] / df["range_miles"]
df["estimated_revenue"] = df["price_usd"] * df["annual_sales_units"]

In [12]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\ericz\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\ericz\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\ericz\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ericz\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "07032006Ez$/" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "EV_Market"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "ev"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'ev' in database 'EV_Market'.